"""empty message

Revision ID: 93a574e50cbc
Revises: 44d41458b5cc
Create Date: 2022-08-02 19:14:21.434973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a574e50cbc'
down_revision = '44d41458b5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_phone_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_phone_key', 'users', ['phone'])
    # ### end Alembic commands ###
