"""empty message

Revision ID: 8d4362b7d84f
Revises: e6b24f64f013
Create Date: 2022-08-04 18:14:42.566578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4362b7d84f'
down_revision = 'e6b24f64f013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'total',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'total',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
